# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-11 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='EventLog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='EventLog',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
